trailingComma: 'es5'
tabWidth: 2
semi: false
singleQuote: true
singleAttributePerLine: true
bracketSpacing: true
plugins:
  - 'prettier-plugin-tailwindcss'
tailwindFunctions: ['clsx', 'cn', 'classNames']
