extends:
  - '@pluralsh/stylelint-config'
  - 'stylelint-config-prettier'
ignoreFiles: ['']
rules:
  plugin/no-unsupported-browser-features:
    - true
    - browsers:
        - '> 1%'
        - Last 4 versions
      ignore:
        - fontface
      ignorePartialSupport: true
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - '@tailwind'
        - 'tailwind'
