apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketing-website-netlify-proxy
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "marketingsite=ghcr.io/pluralsh/marketing"
    argocd-image-updater.argoproj.io/marketingsite.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/marketingsite.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd # can also be git
spec:
  project: default
  source:
    repoURL: 'https://github.com/pluralsh/marketing.git'
    path: netlify-proxy-helm
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: marketing-website
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
