// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  benefits: dynamic(() => import('./Benefits')),
  blog: dynamic(() => import('./Blog')),
  call_to_action: dynamic(() => import('./CallToAction')),
  contact: dynamic(() => import('./Contact')),
  features: dynamic(() => import('./Features')),
  hero: dynamic(() => import('./Hero')),
  logotypes: dynamic(() => import('./Logotypes')),
  navigation_item: dynamic(() => import('./NavigationItem')),
  open_positions: dynamic(() => import('./OpenPositions')),
  pricing: dynamic(() => import('./Pricing')),
  rich_text: dynamic(() => import('./RichText')),
  separator: dynamic(() => import('./Separator')),
  spacer: dynamic(() => import('./Spacer')),
  stats: dynamic(() => import('./Stats')),
  table: dynamic(() => import('./Table')),
  team: dynamic(() => import('./Team')),
  testimonials: dynamic(() => import('./Testimonials')),
  text_media: dynamic(() => import('./TextMedia')),
  tilted_paragraphs: dynamic(() => import('./TiltedParagraphs')),
}
