import type React from 'react'

import { cn } from '@/utils/cn'
import { getPrismicDefaultLanguage } from '@/utils/prismicio'

import '../globals.css'
import { Articulat } from '../[locale]/layout'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: React.PropsWithChildren) {
  const lang = await getPrismicDefaultLanguage()

  return (
    <html lang={lang}>
      <body className={cn(Articulat.className)}>{children}</body>
    </html>
  )
}
